### ISSUE TITLE
Change default compute resource for GCP

### ISSUE THREAD

**Issue by gruberdev** [gruberdev/tf-free#154]
# Description:
 
- Today's default value create a machine of type `f1-micro`, which is deprecated and at the end of 2021 will be switched to the type `e2-micro`. 

# Planned changes:

- Change default value to the new resource type
- Run tests and ensure the testing behavior is similar if not identical

**Comment by nandhae** [comment]
Hello there, Can I pick this one up?

**Comment by gruberdev** [comment]
I am afraid I didn't see it and already implemented it. You can review my PR at least, I've added you to the list of collaborators.
